### ISSUE TITLE
Benchmark SourceNode.fromStringWithSourceMap as well

### ISSUE THREAD

**Issue by bmeurer** [v8/web-tooling-benchmark#19]
@sokra mentioned that webpack often uses `SourceNode.fromStringWithSourceMap` heavily to combine source maps transitively. We currently don't cover that, but should probably include it as well.

**Comment by alopezsanchez** [comment]
Hello!

I'm taking a look, but I'm not sure how to approach this. Shoud it be in the same test file? Something like this maybe? https://gist.github.com/alopezsanchez/6ffb0bac324436cb26976d6447e8887d

Can you help me? 😃 

Thank you!

**Comment by bmeurer** [comment]
Hey @alopezsanchez,

That's awesome, thanks! I think it's ok to have it as part of the `source-maps` test, so in the same test file. Do you have numbers how the score is affected?

**Comment by alopezsanchez** [comment]
Well, without SourceNode.fromStringWithSourceMap...

![screenshot1](https://user-images.githubusercontent.com/15221596/37624616-08ba7868-2bc9-11e8-95d9-23eea21ce4aa.png)

And with it...

![screenshot2](https://user-images.githubusercontent.com/15221596/37624649-21f416d6-2bc9-11e8-8c66-137c921bf548.png)

The code is the same as https://gist.github.com/alopezsanchez/6ffb0bac324436cb26976d6447e8887d

**Comment by mathiasbynens** [comment]
@alopezsanchez Thanks for tackling this! Can you open a PR? We’ll continue the discussion there.
