### ISSUE TITLE
Update package versions

### ISSUE THREAD

**Issue by alopezsanchez** [v8/web-tooling-benchmark#31]
Hello. 

This issue is related to #18.

First, i ran a `npm outdated`:

![captura de pantalla 2018-01-14 a las 22 25 53](https://user-images.githubusercontent.com/15221596/34920879-47bc440a-f97a-11e7-9dc8-1cda8a21a57f.png)

@bmeurer, I have some questions about it:
* Should we upgrade all package versions?
* The reason to have explicit version of packages in `package.json` is the traceability between package versions and project version, right? I mean, having `"prettier": "1.8.2"` instead of `"prettier": "^1.8.2"`, for example.
* This implies a project version bump, right? `0.4.0`?

**Comment by bmeurer** [comment]
Hey @alopezsanchez,

Thanks for kicking this off. Answers to your questions:

- Yes, please upgrade all packages to the latest versions.
- The reason for explicit versions is indeed reproducibility between different builds. All tools/libraries under test need to have explicit versions in the `package.json`.
- Yes, please bump the version to `0.4.0`.

**Comment by mathiasbynens** [comment]
Some drive-by comments:

1. ⁠

    > All tools/libraries under test need to have explicit versions in the `package.json`.

    Let’s add a pre-commit hook that tests for that!

1. ⁠Note that we could also use `package-lock.json` to guarantee reproducibility between different builds.

1. Updating `package.json` can be automated: just run `npx npm-check-updates -a`.

1. Version number bumps should happen in separate commits, IMHO.

**Comment by bmeurer** [comment]
I think I tried `package-lock.json` and that didn't really work as expected. But happy to take patches. Otherwise, +1 to everything you suggested.
