### ISSUE TITLE
Feature request: an easy way to run an individual benchmark

### ISSUE THREAD

**Issue by ajklein** [v8/web-tooling-benchmark#32]
Often, a change will have an effect on only one part of the web-tooling-benchmark. To run one part in isolation, it's required to edit src/suite.js manually and then rerun `npm install`. It'd be nice if this were easier. (thanks to @mathiasbynens for walking me through how to do this manually)

**Comment by bmeurer** [comment]
We could generate all the individual runners at `npm install` time I guess, but that'd take a lot of time to webpack. Maybe having a command line flag to select the tests? Not sure there's a portable way to get to command line arguments in the various JavaScript shells.

**Comment by mathiasbynens** [comment]
> We could generate all the individual runners at `npm install` time I guess, but that'd take a lot of time to webpack. 

I don’t think that’s a big problem, but we don’t have to create all the runners if we don’t want to.

> Maybe having a command line flag to select the tests? Not sure there's a portable way to get to command line arguments in the various JavaScript shells.

We can avoid that problem by passing the CLI flag to the build script. Something like:

```sh
npm run build -- --only=babel
```

This would generate a `dist/cli.js` containing only the Babel benchmark, runnable in the various JS shells.

**Comment by ksashikumar** [comment]
I would like to work on this. If we can do this, we could set this up to run on CI for [babel](https://github.com/babel/babel) which is on the [roadmap](https://github.com/babel/babel/blob/add-roadmap/ROADMAP.md#speed).

**Comment by bmeurer** [comment]
Cool, thanks!

**Comment by mathiasbynens** [comment]
@ksashikumar That would be awesome! See https://github.com/webpack/webpack/issues/2254#issuecomment-203528744 for how this could work with webpack.

**Comment by mathiasbynens** [comment]
Fixed by #34.
