### ISSUE TITLE
uglify-js and uglify-es have correct dependency type?

### ISSUE THREAD

**Issue by alopezsanchez** [v8/web-tooling-benchmark#41]
Hello!

I understand that `uglify-js` and `uglify-es` are `devDependencies` because they are used in the build.
But they are under benchmarking too, so should not they be `dependencies`?

It's just a suggestion.

**Comment by bmeurer** [comment]
Good catch. That looks like an oversight. You wanna submit a PR? 😁

**Comment by alopezsanchez** [comment]
Yes, of course!
